// Generated by Futhark 0.27.0 (prerelease - include info below when reporting bugs).
// git: 8630707600ba26165bf9b51b8064957bef295896
// Compiled with GHC 9.10.3.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *ctx);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_bool_1d;
struct futhark_bool_1d *futhark_new_bool_1d(struct futhark_context *ctx, const bool *data, int64_t dim0);
struct futhark_bool_1d *futhark_new_raw_bool_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
int futhark_values_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr, bool *data);
int futhark_index_bool_1d(struct futhark_context *ctx, bool *out, struct futhark_bool_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
const int64_t *futhark_shape_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
struct futhark_f32_1d;
struct futhark_f32_1d *futhark_new_f32_1d(struct futhark_context *ctx, const float *data, int64_t dim0);
struct futhark_f32_1d *futhark_new_raw_f32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
int futhark_values_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr, float *data);
int futhark_index_f32_1d(struct futhark_context *ctx, float *out, struct futhark_f32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
const int64_t *futhark_shape_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
struct futhark_f32_2d;
struct futhark_f32_2d *futhark_new_f32_2d(struct futhark_context *ctx, const float *data, int64_t dim0, int64_t dim1);
struct futhark_f32_2d *futhark_new_raw_f32_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr);
int futhark_values_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr, float *data);
int futhark_index_f32_2d(struct futhark_context *ctx, float *out, struct futhark_f32_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr);
const int64_t *futhark_shape_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr);
struct futhark_f32_3d;
struct futhark_f32_3d *futhark_new_f32_3d(struct futhark_context *ctx, const float *data, int64_t dim0, int64_t dim1, int64_t dim2);
struct futhark_f32_3d *futhark_new_raw_f32_3d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1, int64_t dim2);
int futhark_free_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr);
int futhark_values_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr, float *data);
int futhark_index_f32_3d(struct futhark_context *ctx, float *out, struct futhark_f32_3d *arr, int64_t i0, int64_t i1, int64_t i2);
unsigned char *futhark_values_raw_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr);
const int64_t *futhark_shape_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr);
struct futhark_i32_1d;
struct futhark_i32_1d *futhark_new_i32_1d(struct futhark_context *ctx, const int32_t *data, int64_t dim0);
struct futhark_i32_1d *futhark_new_raw_i32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
int futhark_values_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr, int32_t *data);
int futhark_index_i32_1d(struct futhark_context *ctx, int32_t *out, struct futhark_i32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
const int64_t *futhark_shape_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
struct futhark_i64_2d;
struct futhark_i64_2d *futhark_new_i64_2d(struct futhark_context *ctx, const int64_t *data, int64_t dim0, int64_t dim1);
struct futhark_i64_2d *futhark_new_raw_i64_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr);
int futhark_values_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr, int64_t *data);
int futhark_index_i64_2d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr);
const int64_t *futhark_shape_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr);
struct futhark_u32_1d;
struct futhark_u32_1d *futhark_new_u32_1d(struct futhark_context *ctx, const uint32_t *data, int64_t dim0);
struct futhark_u32_1d *futhark_new_raw_u32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_u32_1d(struct futhark_context *ctx, struct futhark_u32_1d *arr);
int futhark_values_u32_1d(struct futhark_context *ctx, struct futhark_u32_1d *arr, uint32_t *data);
int futhark_index_u32_1d(struct futhark_context *ctx, uint32_t *out, struct futhark_u32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_u32_1d(struct futhark_context *ctx, struct futhark_u32_1d *arr);
const int64_t *futhark_shape_u32_1d(struct futhark_context *ctx, struct futhark_u32_1d *arr);
struct futhark_u64_1d;
struct futhark_u64_1d *futhark_new_u64_1d(struct futhark_context *ctx, const uint64_t *data, int64_t dim0);
struct futhark_u64_1d *futhark_new_raw_u64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr);
int futhark_values_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr, uint64_t *data);
int futhark_index_u64_1d(struct futhark_context *ctx, uint64_t *out, struct futhark_u64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr);
const int64_t *futhark_shape_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr);

// Opaque values
struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32;
struct futhark_opaque_tup2_arr1d_f32_arr1d_f32;
struct futhark_opaque_tup2_arr1d_f32_arr1d_i64;
struct futhark_opaque_tup2_arr1d_i64_arr1d_i64;
struct futhark_opaque_tup2_arr1d_u64_arr1d_f32;
struct futhark_opaque_tup3_bool_f32_f32;
struct futhark_opaque_tup2_f32_f32;
struct futhark_opaque_tup2_i64_arr1d_i64;
struct futhark_opaque_tup2_i64_i64;
int futhark_free_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32(struct futhark_context *ctx, struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj);
int futhark_store_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32(struct futhark_context *ctx, const struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj, void **p, size_t *n);
struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *futhark_restore_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32_0(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj);
int futhark_project_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32_1(struct futhark_context *ctx, struct futhark_f32_2d **out, const struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj);
int futhark_project_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32_2(struct futhark_context *ctx, struct futhark_f32_2d **out, const struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj);
int futhark_project_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32_3(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj);
int futhark_project_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32_4(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 *obj);
int futhark_new_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32(struct futhark_context *ctx, struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *f_0, const struct futhark_f32_2d *f_1, const struct futhark_f32_2d *f_2, const struct futhark_f32_1d *f_3, const struct futhark_f32_1d *f_4);
int futhark_free_opaque_tup2_arr1d_f32_arr1d_f32(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 *obj);
int futhark_store_opaque_tup2_arr1d_f32_arr1d_f32(struct futhark_context *ctx, const struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 *futhark_restore_opaque_tup2_arr1d_f32_arr1d_f32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_arr1d_f32_arr1d_f32_0(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 *obj);
int futhark_project_opaque_tup2_arr1d_f32_arr1d_f32_1(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 *obj);
int futhark_new_opaque_tup2_arr1d_f32_arr1d_f32(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *f_0, const struct futhark_f32_1d *f_1);
int futhark_free_opaque_tup2_arr1d_f32_arr1d_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 *obj);
int futhark_store_opaque_tup2_arr1d_f32_arr1d_i64(struct futhark_context *ctx, const struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 *futhark_restore_opaque_tup2_arr1d_f32_arr1d_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_arr1d_f32_arr1d_i64_0(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 *obj);
int futhark_project_opaque_tup2_arr1d_f32_arr1d_i64_1(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 *obj);
int futhark_new_opaque_tup2_arr1d_f32_arr1d_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 **out, const struct futhark_f32_1d *f_0, const struct futhark_i64_1d *f_1);
int futhark_free_opaque_tup2_arr1d_i64_arr1d_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 *obj);
int futhark_store_opaque_tup2_arr1d_i64_arr1d_i64(struct futhark_context *ctx, const struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 *futhark_restore_opaque_tup2_arr1d_i64_arr1d_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_arr1d_i64_arr1d_i64_0(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 *obj);
int futhark_project_opaque_tup2_arr1d_i64_arr1d_i64_1(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 *obj);
int futhark_new_opaque_tup2_arr1d_i64_arr1d_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 **out, const struct futhark_i64_1d *f_0, const struct futhark_i64_1d *f_1);
int futhark_free_opaque_tup2_arr1d_u64_arr1d_f32(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 *obj);
int futhark_store_opaque_tup2_arr1d_u64_arr1d_f32(struct futhark_context *ctx, const struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 *futhark_restore_opaque_tup2_arr1d_u64_arr1d_f32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_arr1d_u64_arr1d_f32_0(struct futhark_context *ctx, struct futhark_u64_1d **out, const struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 *obj);
int futhark_project_opaque_tup2_arr1d_u64_arr1d_f32_1(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 *obj);
int futhark_new_opaque_tup2_arr1d_u64_arr1d_f32(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 **out, const struct futhark_u64_1d *f_0, const struct futhark_f32_1d *f_1);
int futhark_free_opaque_tup3_bool_f32_f32(struct futhark_context *ctx, struct futhark_opaque_tup3_bool_f32_f32 *obj);
int futhark_store_opaque_tup3_bool_f32_f32(struct futhark_context *ctx, const struct futhark_opaque_tup3_bool_f32_f32 *obj, void **p, size_t *n);
struct futhark_opaque_tup3_bool_f32_f32 *futhark_restore_opaque_tup3_bool_f32_f32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup3_bool_f32_f32_0(struct futhark_context *ctx, bool *out, const struct futhark_opaque_tup3_bool_f32_f32 *obj);
int futhark_project_opaque_tup3_bool_f32_f32_1(struct futhark_context *ctx, float *out, const struct futhark_opaque_tup3_bool_f32_f32 *obj);
int futhark_project_opaque_tup3_bool_f32_f32_2(struct futhark_context *ctx, float *out, const struct futhark_opaque_tup3_bool_f32_f32 *obj);
int futhark_new_opaque_tup3_bool_f32_f32(struct futhark_context *ctx, struct futhark_opaque_tup3_bool_f32_f32 **out, const bool f_0, const float f_1, const float f_2);
int futhark_free_opaque_tup2_f32_f32(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 *obj);
int futhark_store_opaque_tup2_f32_f32(struct futhark_context *ctx, const struct futhark_opaque_tup2_f32_f32 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_f32_f32 *futhark_restore_opaque_tup2_f32_f32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_f32_f32_0(struct futhark_context *ctx, float *out, const struct futhark_opaque_tup2_f32_f32 *obj);
int futhark_project_opaque_tup2_f32_f32_1(struct futhark_context *ctx, float *out, const struct futhark_opaque_tup2_f32_f32 *obj);
int futhark_new_opaque_tup2_f32_f32(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float f_0, const float f_1);
int futhark_free_opaque_tup2_i64_arr1d_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_arr1d_i64 *obj);
int futhark_store_opaque_tup2_i64_arr1d_i64(struct futhark_context *ctx, const struct futhark_opaque_tup2_i64_arr1d_i64 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_i64_arr1d_i64 *futhark_restore_opaque_tup2_i64_arr1d_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_i64_arr1d_i64_0(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tup2_i64_arr1d_i64 *obj);
int futhark_project_opaque_tup2_i64_arr1d_i64_1(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_tup2_i64_arr1d_i64 *obj);
int futhark_new_opaque_tup2_i64_arr1d_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_arr1d_i64 **out, const int64_t f_0, const struct futhark_i64_1d *f_1);
int futhark_free_opaque_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_i64 *obj);
int futhark_store_opaque_tup2_i64_i64(struct futhark_context *ctx, const struct futhark_opaque_tup2_i64_i64 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_i64_i64 *futhark_restore_opaque_tup2_i64_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_i64_i64_0(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tup2_i64_i64 *obj);
int futhark_project_opaque_tup2_i64_i64_1(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tup2_i64_i64 *obj);
int futhark_new_opaque_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_i64 **out, const int64_t f_0, const int64_t f_1);

// Entry points
int futhark_entry_add_arrays(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_add_scalar(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_array_max(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0);
int futhark_entry_array_mean(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0);
int futhark_entry_array_min(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0);
int futhark_entry_array_sum(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0);
int futhark_entry_batch_matmul(struct futhark_context *ctx, struct futhark_f32_3d **out, const struct futhark_f32_3d *in0, const struct futhark_f32_3d *in1);
int futhark_entry_clip_fisher(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_compute_lsh(struct futhark_context *ctx, struct futhark_u64_1d **out, const struct futhark_f32_1d *in0, const int64_t in1, const uint64_t in2);
int futhark_entry_compute_natural_grad(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const float in2);
int futhark_entry_compute_ngram_hashes(struct futhark_context *ctx, struct futhark_u64_1d **out, const struct futhark_u32_1d *in0, const int64_t in1);
int futhark_entry_compute_rsf_context(struct futhark_context *ctx, struct futhark_f32_2d **out, const struct futhark_f32_2d *in0, const struct futhark_f32_2d *in1, const struct futhark_f32_2d *in2, const struct futhark_f32_1d *in3, const struct futhark_f32_1d *in4, const float in5);
int futhark_entry_div_arrays(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_div_scalar(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_dot(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_matmul(struct futhark_context *ctx, struct futhark_f32_2d **out, const struct futhark_f32_2d *in0, const struct futhark_f32_2d *in1);
int futhark_entry_mul_arrays(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_mul_scalar(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_rank_segments(struct futhark_context *ctx, struct futhark_f32_1d **out, const uint64_t in0, const struct futhark_u64_1d *in1, const struct futhark_f32_1d *in2);
int futhark_entry_reduce_gradients(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_2d *in0);
int futhark_entry_rgpu_adaptive_weights(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const struct futhark_f32_1d *in2, const struct futhark_f32_1d *in3);
int futhark_entry_rgpu_canonical_signature(struct futhark_context *ctx, uint64_t *out, const int64_t in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2, const struct futhark_i32_1d *in3);
int futhark_entry_rgpu_compute_energy_savings(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_compute_route_cost(struct futhark_context *ctx, float *out, const int64_t in0, const int64_t in1, const int64_t in2, const int64_t in3, const float in4, const float in5);
int futhark_entry_rgpu_compute_route_cost_batch(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2, const struct futhark_i64_1d *in3, const float in4, const float in5);
int futhark_entry_rgpu_compute_xy_route(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_arr1d_i64 **out, const int64_t in0, const int64_t in1, const int64_t in2, const int64_t in3, const int64_t in4);
int futhark_entry_rgpu_core_from_pos(struct futhark_context *ctx, int64_t *out, const int64_t in0, const int64_t in1, const int64_t in2);
int futhark_entry_rgpu_core_neighbors(struct futhark_context *ctx, struct futhark_i64_1d **out, const int64_t in0, const int64_t in1, const int64_t in2);
int futhark_entry_rgpu_core_position(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_i64 **out, const int64_t in0, const int64_t in1);
int futhark_entry_rgpu_core_utilization(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1);
int futhark_entry_rgpu_cross_partition_edges(struct futhark_context *ctx, int64_t *out, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2);
int futhark_entry_rgpu_degree_sequence(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_i64_arr1d_i64 **out, const int64_t in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2);
int futhark_entry_rgpu_distance(struct futhark_context *ctx, int64_t *out, const int64_t in0, const int64_t in1, const int64_t in2);
int futhark_entry_rgpu_edge_distribution(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2);
int futhark_entry_rgpu_entangle(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_entangle_batch(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const struct futhark_f32_1d *in2, const struct futhark_f32_1d *in3);
int futhark_entry_rgpu_fractal_dim(struct futhark_context *ctx, float *out, const struct futhark_u64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2);
int futhark_entry_rgpu_fractal_xform(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const int64_t in2);
int futhark_entry_rgpu_gate_core_check(struct futhark_context *ctx, bool *out, const float in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_gate_core_check_batch(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_f32_1d *in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_hadamard(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1);
int futhark_entry_rgpu_hadamard_batch(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_rgpu_latency(struct futhark_context *ctx, float *out, const int64_t in0, const int64_t in1, const int64_t in2, const float in3, const float in4);
int futhark_entry_rgpu_load_balance(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0);
int futhark_entry_rgpu_measure_prob(struct futhark_context *ctx, float *out, const float in0, const float in1);
int futhark_entry_rgpu_measure_prob_batch(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_rgpu_partition(struct futhark_context *ctx, struct futhark_i64_1d **out, const int64_t in0, const int64_t in1);
int futhark_entry_rgpu_partition_bounds(struct futhark_context *ctx, struct futhark_i64_1d **out, const int64_t in0, const int64_t in1);
int futhark_entry_rgpu_partition_loads(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2, const int64_t in3);
int futhark_entry_rgpu_phase(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const float in2);
int futhark_entry_rgpu_phase_batch(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const struct futhark_f32_1d *in2);
int futhark_entry_rgpu_power_check(struct futhark_context *ctx, struct futhark_opaque_tup3_bool_f32_f32 **out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_rgpu_propagate_edge_quality(struct futhark_context *ctx, struct futhark_i32_1d **out, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i32_1d *in2, const struct futhark_i32_1d *in3, const int64_t in4);
int futhark_entry_rgpu_propagate_edge_weights(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2, const int64_t in3, const int64_t in4, const int64_t in5, const float in6);
int futhark_entry_rgpu_quality_to_weight(struct futhark_context *ctx, float *out, const int32_t in0);
int futhark_entry_rgpu_quality_to_weight_batch(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_i32_1d *in0);
int futhark_entry_rgpu_quantum_corr(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_quantum_corr_batch(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const struct futhark_f32_1d *in2, const struct futhark_f32_1d *in3);
int futhark_entry_rgpu_rel_and(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_rel_or(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_rel_xor(struct futhark_context *ctx, struct futhark_opaque_tup2_f32_f32 **out, const float in0, const float in1, const float in2, const float in3);
int futhark_entry_rgpu_sparsity(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_rgpu_sparsity_ratio(struct futhark_context *ctx, float *out, const struct futhark_f32_1d *in0, const float in1);
int futhark_entry_rgpu_update_weights(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const float in2);
int futhark_entry_rsf_backward(struct futhark_context *ctx, struct futhark_opaque_tup5_arr1d_f32_arr2d_f32_arr2d_f32_arr1d_f32_arr1d_f32 **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const struct futhark_f32_2d *in2, const struct futhark_f32_2d *in3, const struct futhark_f32_1d *in4, const struct futhark_f32_1d *in5, const struct futhark_i64_1d *in6);
int futhark_entry_rsf_forward(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_2d *in1, const struct futhark_f32_2d *in2, const struct futhark_f32_1d *in3, const struct futhark_f32_1d *in4, const struct futhark_i64_1d *in5);
int futhark_entry_rsf_forward_multilayer(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_3d *in1, const struct futhark_f32_3d *in2, const struct futhark_f32_2d *in3, const struct futhark_f32_2d *in4, const struct futhark_i64_2d *in5);
int futhark_entry_select_topk(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f32_arr1d_i64 **out, const int64_t in0, const struct futhark_f32_1d *in1);
int futhark_entry_ssi_find_nearest(struct futhark_context *ctx, int64_t *out, const struct futhark_u64_1d *in0, const struct futhark_u32_1d *in1);
int futhark_entry_ssi_get_topk(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_u64_arr1d_f32 **out, const struct futhark_u64_1d *in0, const struct futhark_f32_1d *in1, const struct futhark_u32_1d *in2, const int64_t in3);
int futhark_entry_ssi_hash_tokens(struct futhark_context *ctx, uint64_t *out, const struct futhark_u32_1d *in0);
int futhark_entry_ssi_similarity(struct futhark_context *ctx, float *out, const struct futhark_u32_1d *in0, const struct futhark_u32_1d *in1);
int futhark_entry_sub_arrays(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_update_fisher(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_f32_1d *in0, const struct futhark_f32_1d *in1, const float in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
