// Generated by Futhark 0.27.0 (prerelease - include info below when reporting bugs).
// git: 8d5a52735e549baec5b7339da2606ad3548742c9
// Compiled with GHC 9.10.3.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#include <cuda.h>
#include <cuda_runtime.h>
#include <nvrtc.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *ctx);
void futhark_context_config_set_default_thread_block_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_grid_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_group_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_num_groups(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_tile_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_reg_tile_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_registers(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_cache(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_threshold(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_unified_memory(struct futhark_context_config *cfg, int flag);
void futhark_context_config_add_nvrtc_option(struct futhark_context_config *cfg, const char *opt);
void futhark_context_config_set_device(struct futhark_context_config *cfg, const char *s);
const char *futhark_context_config_get_program(struct futhark_context_config *cfg);
void futhark_context_config_set_program(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_dump_ptx_to(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_load_ptx_from(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_f16_1d;
struct futhark_f16_1d *futhark_new_f16_1d(struct futhark_context *ctx, const uint16_t *data, int64_t dim0);
struct futhark_f16_1d *futhark_new_raw_f16_1d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0);
int futhark_free_f16_1d(struct futhark_context *ctx, struct futhark_f16_1d *arr);
int futhark_values_f16_1d(struct futhark_context *ctx, struct futhark_f16_1d *arr, uint16_t *data);
int futhark_index_f16_1d(struct futhark_context *ctx, uint16_t *out, struct futhark_f16_1d *arr, int64_t i0);
CUdeviceptr futhark_values_raw_f16_1d(struct futhark_context *ctx, struct futhark_f16_1d *arr);
const int64_t *futhark_shape_f16_1d(struct futhark_context *ctx, struct futhark_f16_1d *arr);
struct futhark_f16_2d;
struct futhark_f16_2d *futhark_new_f16_2d(struct futhark_context *ctx, const uint16_t *data, int64_t dim0, int64_t dim1);
struct futhark_f16_2d *futhark_new_raw_f16_2d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0, int64_t dim1);
int futhark_free_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr);
int futhark_values_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr, uint16_t *data);
int futhark_index_f16_2d(struct futhark_context *ctx, uint16_t *out, struct futhark_f16_2d *arr, int64_t i0, int64_t i1);
CUdeviceptr futhark_values_raw_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr);
const int64_t *futhark_shape_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr);
struct futhark_f16_3d;
struct futhark_f16_3d *futhark_new_f16_3d(struct futhark_context *ctx, const uint16_t *data, int64_t dim0, int64_t dim1, int64_t dim2);
struct futhark_f16_3d *futhark_new_raw_f16_3d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0, int64_t dim1, int64_t dim2);
int futhark_free_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr);
int futhark_values_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr, uint16_t *data);
int futhark_index_f16_3d(struct futhark_context *ctx, uint16_t *out, struct futhark_f16_3d *arr, int64_t i0, int64_t i1, int64_t i2);
CUdeviceptr futhark_values_raw_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr);
const int64_t *futhark_shape_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr);

// Opaque values
struct futhark_opaque_tup2_arr2d_f16_arr2d_f16;
struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16;
struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16;
struct futhark_opaque_tup2_arr1d_f16_arr1d_f16;
int futhark_free_opaque_tup2_arr2d_f16_arr2d_f16(struct futhark_context *ctx, struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 *obj);
int futhark_store_opaque_tup2_arr2d_f16_arr2d_f16(struct futhark_context *ctx, const struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 *futhark_restore_opaque_tup2_arr2d_f16_arr2d_f16(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_arr2d_f16_arr2d_f16_0(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 *obj);
int futhark_project_opaque_tup2_arr2d_f16_arr2d_f16_1(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 *obj);
int futhark_new_opaque_tup2_arr2d_f16_arr2d_f16(struct futhark_context *ctx, struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 **out, const struct futhark_f16_2d *f_0, const struct futhark_f16_2d *f_1);
int futhark_free_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16(struct futhark_context *ctx, struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *obj);
int futhark_store_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16(struct futhark_context *ctx, const struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *obj, void **p, size_t *n);
struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *futhark_restore_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_0(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *obj);
int futhark_project_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_1(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *obj);
int futhark_project_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_2(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *obj);
int futhark_project_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_3(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 *obj);
int futhark_new_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16(struct futhark_context *ctx, struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 **out, const struct futhark_f16_2d *f_0, const struct futhark_f16_2d *f_1, const struct futhark_f16_1d *f_2, const struct futhark_f16_1d *f_3);
int futhark_free_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16(struct futhark_context *ctx, struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_store_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16(struct futhark_context *ctx, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj, void **p, size_t *n);
struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *futhark_restore_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_0(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_1(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_2(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_3(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_4(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_5(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_6(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_7(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_project_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16_8(struct futhark_context *ctx, uint16_t *out, const struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 *obj);
int futhark_new_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16(struct futhark_context *ctx, struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 **out, const struct futhark_f16_2d *f_0, const struct futhark_f16_2d *f_1, const struct futhark_f16_1d *f_2, const struct futhark_f16_1d *f_3, const struct futhark_f16_2d *f_4, const struct futhark_f16_2d *f_5, const struct futhark_f16_1d *f_6, const struct futhark_f16_1d *f_7, const uint16_t f_8);
int futhark_free_opaque_tup2_arr1d_f16_arr1d_f16(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 *obj);
int futhark_store_opaque_tup2_arr1d_f16_arr1d_f16(struct futhark_context *ctx, const struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 *futhark_restore_opaque_tup2_arr1d_f16_arr1d_f16(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_arr1d_f16_arr1d_f16_0(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 *obj);
int futhark_project_opaque_tup2_arr1d_f16_arr1d_f16_1(struct futhark_context *ctx, struct futhark_f16_1d **out, const struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 *obj);
int futhark_new_opaque_tup2_arr1d_f16_arr1d_f16(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 **out, const struct futhark_f16_1d *f_0, const struct futhark_f16_1d *f_1);

// Entry points
int futhark_entry_accumulate_gradients(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_f16_2d *in0, const struct futhark_f16_2d *in1);
int futhark_entry_batch_compute_loss(struct futhark_context *ctx, uint16_t *out, const struct futhark_f16_3d *in0, const struct futhark_f16_3d *in1);
int futhark_entry_batch_forward(struct futhark_context *ctx, struct futhark_f16_3d **out, const struct futhark_f16_3d *in0, const struct futhark_f16_2d *in1, const struct futhark_f16_2d *in2, const struct futhark_f16_1d *in3, const struct futhark_f16_1d *in4, const uint16_t in5, const uint16_t in6);
int futhark_entry_batch_gradients(struct futhark_context *ctx, struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 **out, const struct futhark_f16_3d *in0, const struct futhark_f16_3d *in1, const struct futhark_f16_2d *in2, const struct futhark_f16_2d *in3, const struct futhark_f16_1d *in4, const struct futhark_f16_1d *in5, const uint16_t in6, const uint16_t in7);
int futhark_entry_compute_loss(struct futhark_context *ctx, uint16_t *out, const struct futhark_f16_2d *in0, const struct futhark_f16_2d *in1);
int futhark_entry_rsf_backward(struct futhark_context *ctx, struct futhark_opaque_tup4_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16 **out, const struct futhark_f16_2d *in0, const struct futhark_f16_2d *in1, const struct futhark_f16_2d *in2, const struct futhark_f16_2d *in3, const struct futhark_f16_1d *in4, const struct futhark_f16_1d *in5, const uint16_t in6, const uint16_t in7);
int futhark_entry_rsf_forward(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_f16_2d *in0, const struct futhark_f16_2d *in1, const struct futhark_f16_2d *in2, const struct futhark_f16_1d *in3, const struct futhark_f16_1d *in4, const uint16_t in5, const uint16_t in6);
int futhark_entry_scale_weights_inplace(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_f16_2d *in0, const uint16_t in1);
int futhark_entry_sfd_update_bias(struct futhark_context *ctx, struct futhark_opaque_tup2_arr1d_f16_arr1d_f16 **out, const struct futhark_f16_1d *in0, const struct futhark_f16_1d *in1, const uint16_t in2, const uint16_t in3, const struct futhark_f16_1d *in4);
int futhark_entry_sfd_update_half(struct futhark_context *ctx, struct futhark_opaque_tup2_arr2d_f16_arr2d_f16 **out, const struct futhark_f16_2d *in0, const struct futhark_f16_2d *in1, const uint16_t in2, const uint16_t in3, const struct futhark_f16_2d *in4);
int futhark_entry_training_step(struct futhark_context *ctx, struct futhark_opaque_tup9_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_arr2d_f16_arr2d_f16_arr1d_f16_arr1d_f16_f16 **out, const struct futhark_f16_3d *in0, const struct futhark_f16_3d *in1, const struct futhark_f16_2d *in2, const struct futhark_f16_2d *in3, const struct futhark_f16_1d *in4, const struct futhark_f16_1d *in5, const struct futhark_f16_2d *in6, const struct futhark_f16_2d *in7, const struct futhark_f16_1d *in8, const struct futhark_f16_1d *in9, const uint16_t in10, const uint16_t in11, const uint16_t in12, const uint16_t in13);
int futhark_entry_xavier_fill_inplace(struct futhark_context *ctx, struct futhark_f16_2d **out, const struct futhark_f16_2d *in0, const int32_t in1);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_cuda
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
